# Generated by Django 5.0.11 on 2025-04-04 17:05

import schedurec.urec.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('registration_deadline', models.DateTimeField(default=schedurec.urec.models.default_registration_deadline)),
            ],
        ),
    ]
