# Generated by Django 5.0.11 on 2025-04-04 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
